### ISSUE TITLE
 Issue: B506:yaml_load

### ISSUE THREAD

**Issue by IndexSeek** [learning-the-computers/dot-connect#34]
**Describe the bug**
Test results:
>> Issue: [B506:yaml_load] Use of unsafe yaml load. Allows instantiation of arbitrary objects. Consider yaml.safe_load().
   Severity: Medium   Confidence: High
   Location: dot_connect/__init__.py:87
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b506_yaml_load.html
86          with open(file) as f:
87              connection_parameters = yaml.load(f, Loader=yaml.FullLoader)
88

**Expected behavior**
Load safely! :) 

After this fix, will look to add the following pre-commit hook:

```yaml
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit
        args: ["--exclude", 'tests/']
```
